/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logisticaigu;

/**
 *
 * @author ULTRA
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Registrarenvio = new javax.swing.JButton();
        Consultarestadopaquete = new javax.swing.JButton();
        Registrarmantenimiento = new javax.swing.JButton();
        Gestionarentrega = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Encomiendas Patria");

        Registrarenvio.setText("Registrar Envio");
        Registrarenvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarenvioActionPerformed(evt);
            }
        });

        Consultarestadopaquete.setText("Consultar estado del paquete");
        Consultarestadopaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarestadopaqueteActionPerformed(evt);
            }
        });

        Registrarmantenimiento.setText("Registrar Mantenimiento");
        Registrarmantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarmantenimientoActionPerformed(evt);
            }
        });

        Gestionarentrega.setText("Gestionar entrega");
        Gestionarentrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarentregaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Consultarestadopaquete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Registrarenvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Registrarmantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Gestionarentrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(Registrarenvio)
                .addGap(42, 42, 42)
                .addComponent(Consultarestadopaquete)
                .addGap(40, 40, 40)
                .addComponent(Registrarmantenimiento)
                .addGap(36, 36, 36)
                .addComponent(Gestionarentrega)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarmantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarmantenimientoActionPerformed
       RegistrarMantenimiento ventanaMantenimiento = new RegistrarMantenimiento();
    
    // Hacer visible la nueva ventana
    ventanaMantenimiento.setVisible(true);
    
    // Opcional: Cierra la ventana actual (Menu) si lo deseas
    this.dispose();
    }//GEN-LAST:event_RegistrarmantenimientoActionPerformed

    private void RegistrarenvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarenvioActionPerformed
        RegistrarEnvio ventanaRegistro = new RegistrarEnvio();
    
    // Hacer visible la nueva ventana
    ventanaRegistro.setVisible(true);
    
    // Opcional: Cierra la ventana actual (Menu) si lo deseas
    this.dispose();
    }//GEN-LAST:event_RegistrarenvioActionPerformed

    private void ConsultarestadopaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarestadopaqueteActionPerformed
         ConsultarEstadoPaquete  consultapaquete = new ConsultarEstadoPaquete();
         
         consultapaquete.setVisible(true);
         
         this.dispose();
     
     
    
    }//GEN-LAST:event_ConsultarestadopaqueteActionPerformed

    private void GestionarentregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarentregaActionPerformed
        GestionarEntrega gestionentrega = new GestionarEntrega();
        gestionentrega.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GestionarentregaActionPerformed

   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultarestadopaquete;
    private javax.swing.JButton Gestionarentrega;
    private javax.swing.JButton Registrarenvio;
    private javax.swing.JButton Registrarmantenimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables



}
