/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logisticaigu;

import Controladoras.ControladoraVehiculo;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import logisticalogica.Vehiculo;

/**
 *
 * @author ULTRA
 */
public class RegistrarMantenimiento extends javax.swing.JFrame {

   ControladoraVehiculo controladoraVehiculo = new ControladoraVehiculo();
   public static Vehiculo vehiculoSeleccionado;
   private List<Vehiculo> vehiculos;


    public RegistrarMantenimiento() {
        initComponents();
        mostrarTodosLosVehiculos();
        inicializarVentana();

         Ingresarpatente.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent evt) {
            filtrarPorPatente();
        }

        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent evt) {
            filtrarPorPatente();
        }

        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent evt) {
            filtrarPorPatente();
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Ingresarpatente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablafiltrar = new javax.swing.JTable();
        Ingresarmarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Mantenimiento");

        jLabel2.setText("Patente:");

        Ingresarpatente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarpatenteActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        tablafiltrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Marca", "Capacidad de carga", "N° de vehiculo", "Patente"
            }
        ));
        jScrollPane1.setViewportView(tablafiltrar);

        Ingresarmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarmarcaActionPerformed(evt);
            }
        });

        jLabel3.setText("Marca:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(Ingresarmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ingresarpatente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Aceptar)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ingresarpatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Ingresarmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(jButton1))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarmarcaActionPerformed
    filtrarPorModelo();
    }//GEN-LAST:event_IngresarmarcaActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
    ConfirmarMantenimiento ventanaConfirmar = new ConfirmarMantenimiento();
        ventanaConfirmar.inicializarVentana();

    ventanaConfirmar.setVisible(true);
    this.dispose(); // Cierra la ventana actual, si se desea
    }//GEN-LAST:event_AceptarActionPerformed

    private void IngresarpatenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarpatenteActionPerformed
        filtrarPorPatente();
    }//GEN-LAST:event_IngresarpatenteActionPerformed

    /**
     * @param args the command line arguments
     */
   private void filtrarPorPatente() {
    String patente = Ingresarpatente.getText();
    vehiculos = controladoraVehiculo.filtrarVehiculosPorPatente(patente);
    mostrarVehiculosEnTabla(vehiculos);
}
    private void filtrarPorModelo() {
    String modelo = Ingresarmarca.getText();

    if (modelo.isEmpty()) {
        mostrarTodosLosVehiculos(); // Muestra todos los vehículos si el campo está vacío
    } else {
        // Asignar los vehículos filtrados a la lista de vehículos de la clase
        vehiculos = controladoraVehiculo.filtrarVehiculosPorModeloCoincidente(modelo);
        mostrarVehiculosEnTabla(vehiculos);
    }
}


private void mostrarVehiculosEnTabla(List<Vehiculo> vehiculos) {
        DefaultTableModel modelo = (DefaultTableModel) tablafiltrar.getModel();
        modelo.setRowCount(0); // Elimina todas las filas existentes en la tabla

        for (Vehiculo vehiculo : vehiculos) {
            modelo.addRow(new Object[]{
                vehiculo.getMarca().getModelo(), 
                vehiculo.getCapacidad_carga(), 
                vehiculo.getNro_vehiculo(), 
                vehiculo.getPatente()
            });
        }
    }

    // Método para inicializar la ventana
    private void inicializarVentana() {
        // Agregar el listener a la tabla para capturar la selección del usuario
        tablafiltrar.getSelectionModel().addListSelectionListener(e -> {
            int selectedRow = tablafiltrar.getSelectedRow();
            if (selectedRow >= 0) {
                // Obtener el vehículo seleccionado en la tabla
                vehiculoSeleccionado = vehiculos.get(selectedRow);
            }
        });
    }



private void mostrarTodosLosVehiculos() {
    // Asignar los vehículos obtenidos a la lista de vehículos de la clase
    vehiculos = controladoraVehiculo.obtenerTodosLosVehiculos();
    mostrarVehiculosEnTabla(vehiculos);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JTextField Ingresarmarca;
    private javax.swing.JTextField Ingresarpatente;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablafiltrar;
    // End of variables declaration//GEN-END:variables
}
